language: go
go:
  - 1.6
  - 1.7
notificaitons:
  email:
    recipients:
      gomatic@nicerobot.org
    on_success: change
    on_failure: always
install:
  - go get -t ./...
  - export PATH=$PATH:$HOME/gopath/bin
script:
  - go test -v
